"""add: translated_text for fetched_entity

Revision ID: ef153b59ff45
Revises: b1ec2e8ee81b
Create Date: 2026-09-13 07:00:38.360159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef153b59ff45'
down_revision: Union[str, Sequence[str], None] = 'b1ec2e8ee81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fetched_entity', sa.Column('translated_text', sa.Text(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'unset'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'unset'"))
    op.drop_column('fetched_entity', 'translated_text')
    # ### end Alembic commands ###
